name: coaching-system
app_id: da_2qMIbt8UODz5
owner: eddycollart
package: .
locality:
  regions:
  - fr-pari1
capabilities:
  database:
    engine: mysql
debug: true
scaling:
  mode: single_concurrency
kind: wasmer.io/App.v0
