sonar.projectKey=collaed_dscoach
sonar.organization=collaed
sonar.projectName=DSCoaching

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

sonar.exclusions=lib/**,static/**,src/templates/**,src/db.py,src/db_pg.py,src/server_docker.py
sonar.test.exclusions=lib/**
