[package]
name = "eddycollart/coaching-system"
version = "0.21.0"
description = "1-to-many coaching relationship management system"
readme = "README.md"

[dependencies]
"wasmer/python" = "^3.12.6"

[fs]
"/src" = "./src"
"/static" = "./static"
"/lib" = "./lib"

[[command]]
name = "script"
module = "wasmer/python:python"
runner = "wasi"

[command.annotations.wasi]
main-args = ["-u", "/src/server.py"]
env = ["PYTHONEXECUTABLE: /bin/python"]
